from PyQt5 import QtCore, QtGui, QtWidgets
from client_core import user_fetch, file_upload_server,data_dedup_check, data_refresh_func, logout_handler
from PyQt5.QtCore import QDir
from PyQt5.QtWidgets import QFileDialog
import os
import datetime
import math



class Ui_userpofile(object):
    def __init__(self, uname):
        self.username = uname
        self.user_info(self.username)

    def setupUi(self, userpofile):
        userpofile.setObjectName("userpofile")
        userpofile.setFixedSize(768, 600)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(10)
        userpofile.setFont(font)
        self.centralwidget = QtWidgets.QWidget(userpofile)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 70, 711, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 110, 711, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(40, 40, 91, 21))
        self.label_3.setObjectName("label_3")
        self.add_btn = QtWidgets.QPushButton(self.tab)
        self.add_btn.setGeometry(QtCore.QRect(650, 75, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(18)
        self.add_btn.setFont(font)
        self.add_btn.setObjectName("add_btn")
        self.filepath_fld = QtWidgets.QLineEdit(self.tab)
        self.filepath_fld.setGeometry(QtCore.QRect(120, 80, 511, 21))
        self.filepath_fld.setObjectName("filepath_fld")
        self.cancel_btn = QtWidgets.QPushButton(self.tab)
        self.cancel_btn.setGeometry(QtCore.QRect(480, 120, 93, 28))
        self.cancel_btn.setObjectName("cancel_btn")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 81, 21))
        self.label_2.setObjectName("label_2")
        self.upload_btn = QtWidgets.QPushButton(self.tab)
        self.upload_btn.setGeometry(QtCore.QRect(590, 120, 93, 28))
        self.upload_btn.setObjectName("upload_btn")
        self.upload_status = QtWidgets.QLabel(self.tab)
        self.upload_status.setGeometry(QtCore.QRect(200, 40, 201, 19))
        self.upload_status.setObjectName("upload_status")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(40, 180, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(60, 250, 91, 19))
        self.label_5.setObjectName("label_5")

        self.filename_label = QtWidgets.QLabel(self.tab)
        self.filename_label.setGeometry(QtCore.QRect(60, 220, 91, 19))
        self.filename_label.setObjectName("filename_label")

        self.filename_fld = QtWidgets.QLabel(self.tab)
        self.filename_fld.setGeometry(QtCore.QRect(160, 220, 251, 19))
        self.filename_fld.setObjectName("filename_fld")

        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(60, 280, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(60, 310, 91, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(60, 340, 91, 19))
        self.label_9.setObjectName("label_9")
        self.file_type_label = QtWidgets.QLabel(self.tab)
        self.file_type_label.setGeometry(QtCore.QRect(160, 250, 101, 19))
        self.file_type_label.setObjectName("file_type_label")
        self.file_loc_label = QtWidgets.QLabel(self.tab)
        self.file_loc_label.setGeometry(QtCore.QRect(160, 280, 521, 19))
        self.file_loc_label.setObjectName("file_loc_label")
        self.file_size_label = QtWidgets.QLabel(self.tab)
        self.file_size_label.setGeometry(QtCore.QRect(160, 310, 101, 19))
        self.file_size_label.setObjectName("file_size_label")
        self.file_crearted_label = QtWidgets.QLabel(self.tab)
        self.file_crearted_label.setGeometry(QtCore.QRect(160, 340, 151, 19))
        self.file_crearted_label.setObjectName("file_crearted_label")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(20, 10, 651, 161))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.files_present_label = QtWidgets.QLabel(self.frame)
        self.files_present_label.setGeometry(QtCore.QRect(40, 38, 241, 20))
        self.files_present_label.setObjectName("files_present_label")
        self.file_size_label_2 = QtWidgets.QLabel(self.frame)
        self.file_size_label_2.setGeometry(QtCore.QRect(40, 68, 131, 20))
        self.file_size_label_2.setObjectName("file_size_label_2")
        self.total_files = QtWidgets.QLabel(self.frame)
        self.total_files.setGeometry(QtCore.QRect(290, 40, 21, 16))
        self.total_files.setObjectName("total_files")
        self.files_size = QtWidgets.QLabel(self.frame)
        self.files_size.setGeometry(QtCore.QRect(290, 68, 101, 19))
        self.files_size.setObjectName("files_size")
        self.refresh_btn = QtWidgets.QPushButton(self.frame)
        self.refresh_btn.setGeometry(QtCore.QRect(410, 118, 93, 28))
        self.refresh_btn.setObjectName("refresh_btn")
        self.data_check_btn = QtWidgets.QPushButton(self.frame)
        self.data_check_btn.setGeometry(QtCore.QRect(310, 118, 93, 28))
        self.data_check_btn.setObjectName("data_check_btn")
        self.open_file_explorer = QtWidgets.QPushButton(self.frame)
        self.open_file_explorer.setGeometry(QtCore.QRect(510, 118, 131, 28))
        self.open_file_explorer.setObjectName("open_file_explorer")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 8, 101, 21))
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(30, 280, 71, 16))
        self.label_10.setObjectName("label_10")
        self.console_output = QtWidgets.QPlainTextEdit(self.tab_2)
        self.console_output.setGeometry(QtCore.QRect(30, 310, 641, 61))
        self.console_output.setObjectName("console_output")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(20, 170, 651, 111))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_21 = QtWidgets.QLabel(self.frame_3)
        self.label_21.setGeometry(QtCore.QRect(50, 40, 81, 21))
        self.label_21.setObjectName("label_21")
        self.add_btn_3 = QtWidgets.QPushButton(self.frame_3)
        self.add_btn_3.setGeometry(QtCore.QRect(610, 35, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(18)
        self.add_btn_3.setFont(font)
        self.add_btn_3.setObjectName("add_btn_3")
        self.download_btn = QtWidgets.QPushButton(self.frame_3)
        self.download_btn.setGeometry(QtCore.QRect(550, 80, 93, 28))
        self.download_btn.setObjectName("download_btn")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label_20.setObjectName("label_20")
        self.download_filepath_fld = QtWidgets.QLineEdit(self.frame_3)
        self.download_filepath_fld.setGeometry(QtCore.QRect(130, 40, 471, 21))
        self.download_filepath_fld.setObjectName("download_filepath_fld")
        self.cancel_downlaod_btn = QtWidgets.QPushButton(self.frame_3)
        self.cancel_downlaod_btn.setGeometry(QtCore.QRect(440, 80, 93, 28))
        self.cancel_downlaod_btn.setObjectName("cancel_downlaod_btn")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.user_online = QtWidgets.QLabel(self.tab_3)
        self.user_online.setGeometry(QtCore.QRect(50, 20, 121, 16))
        self.user_online.setObjectName("user_online")
        self.user_online_refresh_btn = QtWidgets.QPushButton(self.tab_3)
        self.user_online_refresh_btn.setGeometry(QtCore.QRect(50, 50, 93, 28))
        self.user_online_refresh_btn.setObjectName("user_online_refresh_btn")
        self.tabWidget.addTab(self.tab_3, "")
        self.logout_btn = QtWidgets.QPushButton(self.centralwidget)
        self.logout_btn.setGeometry(QtCore.QRect(650, 30, 93, 28))
        self.logout_btn.setObjectName("logout_btn")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(160, 30, 191, 31))

        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setText(self.name)
        self.label_22.setObjectName("label_22")
        self.label_22.setStyleSheet("color: red")
        userpofile.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(userpofile)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 27))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        userpofile.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(userpofile)
        self.statusbar.setObjectName("statusbar")
        userpofile.setStatusBar(self.statusbar)
        self.actionAbout_Us = QtWidgets.QAction(userpofile)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(9)
        self.actionAbout_Us.setFont(font)
        self.actionAbout_Us.setObjectName("actionAbout_Us")
        self.actionHow_to_help = QtWidgets.QAction(userpofile)
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setPointSize(9)
        self.actionHow_to_help.setFont(font)
        self.actionHow_to_help.setObjectName("actionHow_to_help")
        self.actionFeedback = QtWidgets.QAction(userpofile)
        self.actionFeedback.setObjectName("actionFeedback")
        self.menuHelp.addAction(self.actionFeedback)
        self.menuHelp.addAction(self.actionHow_to_help)
        self.menuHelp.addAction(self.actionAbout_Us)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(userpofile)
        self.tabWidget.setCurrentIndex(0)
        self.cancel_btn.clicked.connect(self.filepath_fld.clear)
        self.cancel_btn.clicked.connect(self.filename_fld.clear)
        self.cancel_btn.clicked.connect(self.file_type_label.clear)
        self.cancel_btn.clicked.connect(self.file_loc_label.clear)
        self.cancel_btn.clicked.connect(self.file_size_label.clear)
        self.cancel_btn.clicked.connect(self.file_crearted_label.clear)
        self.cancel_downlaod_btn.clicked.connect(self.download_filepath_fld.clear)
        QtCore.QMetaObject.connectSlotsByName(userpofile)

    def retranslateUi(self, userpofile):
        _translate = QtCore.QCoreApplication.translate
        userpofile.setWindowTitle(_translate("userpofile", f"{self.name}"))
        self.label.setText(_translate("userpofile", "Welcome"))
        self.label_3.setText(_translate("userpofile", "Upload File"))
        self.add_btn.setText(_translate("userpofile", "+"))
        self.cancel_btn.setText(_translate("userpofile", "Cancel"))
        self.label_2.setText(_translate("userpofile", "File path :"))
        self.upload_btn.setText(_translate("userpofile", "Upload"))
        self.upload_status.setText(_translate("userpofile", " "))
        self.label_4.setText(_translate("userpofile", "File Details:"))
        self.label_5.setText(_translate("userpofile", "Type of file:"))
        self.filename_label.setText(_translate("userpofile", "File name:"))
        self.filename_fld.setText(_translate("userpofile", " "))
        self.label_6.setText(_translate("userpofile", "Location:"))
        self.label_8.setText(_translate("userpofile", "Size:"))
        self.label_9.setText(_translate("userpofile", "Created on:"))
        self.file_type_label.setText(_translate("userpofile", " "))
        self.file_loc_label.setText(_translate("userpofile", " "))
        self.file_size_label.setText(_translate("userpofile", " "))
        self.file_crearted_label.setText(_translate("userpofile", " "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("userpofile", "Upload"))
        self.files_present_label.setText(_translate("userpofile", "Total Files present in the server:"))
        self.file_size_label_2.setText(_translate("userpofile", "Total File sizes :"))
        self.total_files.setText(_translate("userpofile", " "))
        self.files_size.setText(_translate("userpofile", "25KB"))
        self.refresh_btn.setText(_translate("userpofile", "Refresh"))
        self.data_check_btn.setText(_translate("userpofile", "Check"))
        self.open_file_explorer.setText(_translate("userpofile", "Open Explorer"))
        self.label_7.setText(_translate("userpofile", "File Explorer:"))
        self.label_10.setText(_translate("userpofile", "Console:"))
        self.label_21.setText(_translate("userpofile", "File path :"))
        self.add_btn_3.setText(_translate("userpofile", "+"))
        self.download_btn.setText(_translate("userpofile", "Download"))
        self.label_20.setText(_translate("userpofile", "Download:"))
        self.cancel_downlaod_btn.setText(_translate("userpofile", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("userpofile", "Explorer"))
        self.user_online.setText(_translate("userpofile", "User online:"))
        self.user_online_refresh_btn.setText(_translate("userpofile", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("userpofile", "Chat"))
        self.logout_btn.setText(_translate("userpofile", "Logout"))
        self.menuHelp.setTitle(_translate("userpofile", "Help"))
        self.actionAbout_Us.setText(_translate("userpofile", "About Us"))
        self.actionHow_to_help.setText(_translate("userpofile", "How to (help)"))
        self.actionFeedback.setText(_translate("userpofile", "Feedback"))

        self.add_btn.clicked.connect(self.file_dialog)
        self.total_files.setText(self.total_files_data)
        self.files_size.setText(self.files_size_data)
        self.upload_btn.clicked.connect(self.file_upload_handler)
        self.data_check_btn.clicked.connect(self.data_dedup_check)
        self.refresh_btn.clicked.connect(self.data_refresh)
        self.logout_btn.clicked.connect(self.logout_signal)

    def user_info(self, username):
        user_file_data = user_fetch(username)
        data = list(user_file_data)
        self.name = data[0]
        self.total_files_data = data[1]
        self.files_size_data = data[2]

    def file_dialog(self):
        try:
            dialog = QFileDialog()
            dialog.setFileMode(QFileDialog.AnyFile)
            dialog.setFilter(QDir.Files)

            if dialog.exec_():
                file_name = dialog.selectedFiles()
                print(file_name)
                self.file_path = file_name[0]
                self.filepath_fld.setText(self.file_path)
            else:
                self.upload_status.setText("Please select the file")

            if len(self.file_path) != 0:
                raw_size = os.path.getsize(self.file_path)
                self.file_size = self.convert_size(raw_size)
                self.filename = os.path.basename(self.file_path)
                rawfile_type = self.filename.split(".")
                self.file_type = str(rawfile_type[len(rawfile_type) - 1])
                unix_time = os.path.getctime(self.file_path)
                timestamp = datetime.datetime.fromtimestamp(unix_time)
                self.created_on = timestamp.strftime('%d-%m-%y  %H:%M:%S')

                self.filename_fld.setText(self.filename)
                self.file_type_label.setText(self.file_type)
                self.file_loc_label.setText(self.file_path)
                self.file_size_label.setText(str(self.file_size))
                self.file_crearted_label.setText(self.created_on)
            else:
                self.upload_status.setText("Please select the file")

        except Exception as e:
            print(e)

    def convert_size(self, size_bytes):
        if size_bytes == 0:
            return "0B"
        size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
        i = int(math.floor(math.log(size_bytes, 1024)))
        p = math.pow(1024, i)
        s = round(size_bytes / p, 2)
        return "%s %s" % (s, size_name[i])

    def file_upload_handler(self):
        if len(self.filepath_fld.text()) == 0:
            self.upload_status.setText("Please select file to upload")
        else:
            msg = file_upload_server(self.file_path)[0]
            self.upload_status.setText(msg)
            self.filepath_fld.clear()

    def data_dedup_check(self):
        data_handle = data_dedup_check()
        self.console_output.setPlainText(data_handle)

    def data_refresh(self):
        try:
            file_data =data_refresh_func()
            data = list(file_data)
            self.refresh_total_file = data[0]
            self.refresh_file_size = data[1]

            self.total_files.setText(self.refresh_total_file)
            self.files_size.setText(str(self.convert_size(int(self.refresh_file_size))))
        except Exception as e:
            print(e)

    def logout_signal(self):
        logout_handler()
        print("Log out successfully")

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    userpofile = QtWidgets.QMainWindow()
    ui = Ui_userpofile()
    ui.setupUi(userpofile)
    userpofile.show()
    sys.exit(app.exec_())
